### ISSUE TITLE
Internet Explorer - 404 not found for info iframe

### ISSUE THREAD

**Issue by FZambia** [sockjs/sockjs-client#249]
Hello! Just found a problem with Internet Explorer 9.

Using SockJS 1.0.0, in IE9 I came across a problem with connection to SockJS server. When client wants to establish connection from http frontend to https SockJS server client tries to utilize `InfoIframe` receiver so it tries to load info iframe from `https://example.com/connection/info/iframe.html`. SockJS server has no such endpoint so I get 404 error on info request.

Update: changed issue description

**Comment by FZambia** [comment]
I my 404 case SockJS uses `InfoIframe` receiver ([this one](https://github.com/sockjs/sockjs-client/blob/master/dist/sockjs-1.0.0.js#L537))

**Comment by FZambia** [comment]
So correct problem description is:

In my case IE9 uses `InfoIframe` receiver and tries to get info loading iframe from https://example.com/connection/info/iframe.html which is not found on SockJS server. I have not found this endpoint in SockJS-node routes. And I am a bit confused now))

**Comment by FZambia** [comment]
Steps to reproduce in Chrome:

1) Run SockJS server over `http` or `https`

2) Comment all info receivers except `InfoIframe` in SockJS client:
```javascript
InfoReceiver._getReceiver = function(url, urlInfo) {
  // determine method of CORS support (if needed)
  //if (urlInfo.sameOrigin) {
  //  return new InfoAjax(url, XHRLocal);
  //}
  //if (XHRCors.enabled) {
  //  return new InfoAjax(url, XHRCors);
  //}
  //if (XDR.enabled && urlInfo.sameScheme) {
  //  return new InfoAjax(url, XDR);
  //}
  
  if (InfoIframe.enabled()) {
    return new InfoIframe(url);
  }
  return new InfoAjax(url, XHRFake);
};
```

3) Try to connect from browser application.

There is not only 404 while trying to load info iframe but also an exception in console:

```
Uncaught TypeError: Cannot read property 'contentWindow' of null
```

In [this](https://github.com/sockjs/sockjs-client/blob/master/dist/sockjs-1.0.0.js#L3391) line as a result of [cleanup](https://github.com/sockjs/sockjs-client/blob/master/dist/sockjs-1.0.0.js#L3380) after error.

**Comment by brycekahle** [comment]
Do you have the client code that you are using?

**Comment by FZambia** [comment]
Unfortunately I am on vacation at moment without my notebook, will post my simplified client code as soon as come home (in two weeks). There is nothing special I think - it works fine in other browsers when InfoAjax info receiver used.

**Comment by FZambia** [comment]
I [forked](https://github.com/FZambia/sockjs-node) sockjs-node repo and slightly modified echo example: https://github.com/sockjs/sockjs-node/compare/master...FZambia:master

Also added local sockjs 1.0.0 client and [commented everything except InfoIframe receiver](https://github.com/FZambia/sockjs-node/blob/master/examples/echo/sockjs-1.0.0.js#L527) which was used in my original IE9 case. Now it can be reproduced in other browser:

1) Clone repo and go to examples/echo folder
2) npm install
3) node server.js
4) open localhost:9999

**Comment by brycekahle** [comment]
Found the bug and fixed it. It is fixed in v1.0.1

**Comment by FZambia** [comment]
Have you tried to run my example with updated sockjs client? It seems that it still doesn't work. As far as I understand base url for info receiver results in loading iframe for cross-domain transports - but not an iframe with server info. And then I still get 404 for another xhr request (`GET http://localhost:9999/echo?t=1437374349666 404 (Not Found)`)

**Comment by brycekahle** [comment]
I didn't run your example because I thought I saw the issue. I will try your example ASAP to see what you are running into now.

**Comment by brycekahle** [comment]
I ran your example. I see the same error, but that is something different from your initial bug report. I will keep looking into it.

**Comment by brycekahle** [comment]
Fixed the secondary error in b331d9b5cb1ce6122737a4b1136f0ae83449d282. Thanks for the report!

**Comment by FZambia** [comment]
Thanks for fixing! Could you also make new release?

**Comment by brycekahle** [comment]
1.0.2 released
