### ISSUE TITLE
Expose Ecmascript module

### ISSUE THREAD

**Issue by larsvanhilten** [sockjs/sockjs-client#519]
I am using sockjs-client with Angular (10) and getting the following warning:

`WARNING in <file-path> depends on 'sockjs-client'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies`

I believe that in the current state, the library is not tree-shakeable for angular, therefore unnecessary increasing the bundle size.

Is it a possibility to also expose an Ecmascript module?

**Comment by brycekahle** [comment]
That being said, this module is fairly small and doesn't include a bunch of unnecessary dependencies. Tree-shaking may be able to reduce the size, but I wouldn't expect by a large amount.

**Comment by larsvanhilten** [comment]
It shouldn't require an entire rewrite, [here](https://2ality.com/2019/10/hybrid-npm-packages.html) it goes in to more detail. 

Since the package is imported in its entirety and quite small, it's fine for me to leave it as is. You can close the issue if you'd like.

**Comment by brycekahle** [comment]
To get the benefit of tree-shaking, all the imports would need to be changed to ES module imports.

**Comment by mCzolko** [comment]
should be resolved.

**Comment by DaSchTour** [comment]
@larsvanhilten @mCzolko maybe you can help me on this repo https://github.com/modern-socks/sockjs-client to create a modern ES module version of sockjs client.

**Comment by MaKCbIMKo** [comment]
I still see the same message as OP does.

Is there any progress on that?
